"""``chaski.Node``: an embedded colcad (SDK design §3.1, §7 gaps 4-5).

A ``Node`` is a node in exactly the sense a generated headless edge is one:
colcad plus the services publishing through its local door. Configuration is
generated by the SDK, never written by the integrator — loopback addresses
on high ports, a data directory under the caller's home, no TLS doors except
the uplink, ``autobind: on_new_connector``. Because the child opens the
uplink outbound and commands ride the same link, an embedded node needs no
inbound port — which is also why it has no ``/healthz`` a remote operator can
reach: enrollment reads the pubkey locally instead and prints the one-liner
the operator runs on the PARENT (:meth:`enroll_hint`, closing the loop with
``colca node enroll --pubkey`` — gap 2).
"""

from __future__ import annotations

import json
import os
import secrets
import shutil
import socket
import subprocess
import sys
import time
import urllib.request
from pathlib import Path
from typing import Any, Optional

import ulid as ulid_lib
import yaml

from .service import Service

_COLCAD_ENV = "COLCAD_BINARY"


def _free_port() -> int:
    """A currently-free loopback TCP port. Small race (freed, then handed to
    colcad) — the same pattern most local dev tooling accepts; ports are
    persisted in config.yaml once picked so a restart does not reshuffle
    them."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _resolve_colcad_binary() -> str:
    """Where the colcad binary comes from, in order: an explicit override
    (tests, and any caller who already has one), the platform wheel
    (``chaski[node]`` -> ``colcad``, SDK design §6/§7 gap 5), or
    whatever `colcad` resolves to on PATH."""
    override = os.environ.get(_COLCAD_ENV)
    if override:
        return override
    try:
        from colcad import BINARY_PATH  # type: ignore[import-not-found]

        return str(BINARY_PATH)
    except ImportError:
        pass
    found = shutil.which("colcad")
    if found:
        return found
    raise RuntimeError(
        "chaski.Node could not find the colcad binary. Install `chaski[node]` "
        f"for your platform, set {_COLCAD_ENV} to a colcad binary, or put "
        "colcad on PATH."
    )


class Node:
    """An embedded colca node: colcad as a supervised subprocess."""

    def __init__(
        self,
        name: str,
        *,
        parent: Optional[dict[str, str]] = None,
        data_dir: Optional[Path] = None,
        autobind: Optional[str] = "on_new_connector",
        log_level: str = "info",
        binary: Optional[str] = None,
    ) -> None:
        """``parent`` is ``{"url": ..., "pubkey": ...}`` — the same two
        values ``colca node enroll`` prints, or that this node's own parent
        hands out. Omit it for a root (or not-yet-enrolled) node."""
        self.name = name
        self.parent = dict(parent) if parent else None
        self.data_dir = Path(data_dir).expanduser() if data_dir else (Path.home() / ".colca" / name)
        self.autobind = autobind
        self.log_level = log_level
        self._binary = binary
        self._process: Optional[subprocess.Popen] = None
        self.ulid: Optional[str] = None
        self.pubkey: Optional[str] = None
        self.admin_token: Optional[str] = None
        self._ports: dict[str, int] = {}

    # -- configuration -------------------------------------------------

    def _config_path(self) -> Path:
        return self.data_dir / "config.yaml"

    def _load_existing(self) -> Optional[dict[str, Any]]:
        path = self._config_path()
        if not path.exists():
            return None
        return yaml.safe_load(path.read_text(encoding="utf-8")) or None

    def _write_config(self) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)
        (self.data_dir / "store").mkdir(exist_ok=True)
        existing = self._load_existing()
        self.ulid = (existing or {}).get("ulid") or str(ulid_lib.new())
        self.admin_token = (existing or {}).get("api", {}).get("token") or secrets.token_hex(32)
        self._ports = _existing_ports(existing) or {
            "api": _free_port(),
            "api_local": _free_port(),
            "mqtt": _free_port(),
            "mqtt_local": _free_port(),
            "repl": _free_port(),
        }
        doc: dict[str, Any] = {
            "ulid": self.ulid,
            "name": self.name,
            "data_dir": str(self.data_dir / "store"),
            "key_file": str(self.data_dir / "node.key"),
            "log_level": self.log_level,
            "api": {
                "addr": f"127.0.0.1:{self._ports['api']}",
                "local_addr": f"127.0.0.1:{self._ports['api_local']}",
                "token": self.admin_token,
            },
            "mqtt": {"addr": f"127.0.0.1:{self._ports['mqtt']}"},
            "mqtt_local": {"addr": f"127.0.0.1:{self._ports['mqtt_local']}"},
            "repl": {"addr": f"127.0.0.1:{self._ports['repl']}"},
        }
        if self.autobind:
            doc["plugin"] = {"autobind": self.autobind}
        if self.parent:
            doc["parent"] = {"url": self.parent["url"], "pubkey": self.parent["pubkey"]}
        self._config_path().write_text(yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")

    # -- lifecycle -------------------------------------------------------

    def start(self, *, timeout: float = 30.0) -> "Node":
        """Write config, launch colcad, and wait for its local /healthz."""
        if self._process is not None and self._process.poll() is None:
            return self
        binary = self._binary or _resolve_colcad_binary()
        self._write_config()
        self._process = subprocess.Popen(  # noqa: S603 - binary is resolved above, not shell-interpreted
            [binary, str(self._config_path())],
            stdout=sys.stdout,
            stderr=sys.stderr,
        )
        self._wait_healthy(timeout)
        return self

    def _wait_healthy(self, timeout: float) -> None:
        deadline = time.monotonic() + timeout
        url = f"http://127.0.0.1:{self._ports['api_local']}/healthz"
        last_error: Optional[BaseException] = None
        while time.monotonic() < deadline:
            if self._process is not None and self._process.poll() is not None:
                raise RuntimeError(
                    f"colcad exited before becoming healthy (exit code {self._process.returncode})"
                )
            try:
                with urllib.request.urlopen(url, timeout=1.0) as response:  # noqa: S310
                    payload = json.load(response)
                self.pubkey = payload.get("pubkey")
                self.ulid = payload.get("ulid") or self.ulid
                return
            except Exception as exc:  # noqa: BLE001 - retried until the deadline
                last_error = exc
            time.sleep(0.2)
        raise TimeoutError(f"colcad did not become healthy within {timeout}s: {last_error}")

    def stop(self, *, timeout: float = 10.0) -> None:
        if self._process is None:
            return
        self._process.terminate()
        try:
            self._process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            self._process.kill()
            self._process.wait(timeout=timeout)
        self._process = None

    def __enter__(self) -> "Node":
        return self.start()

    def __exit__(self, *exc_info: Any) -> None:
        self.stop()

    # -- placement ---------------------------------------------------------

    def enroll_hint(self, parent_url: str, *, mount: str = "", token_env: str = "COLCA_ADMIN_TOKEN") -> str:
        """The one-liner the parent's operator runs once (gap 2): this
        node's API door is loopback-only by design (no inbound port needed —
        the uplink is outbound), so enrollment reads the pubkey locally
        rather than the parent fetching /healthz itself."""
        if not self.pubkey:
            raise RuntimeError("chaski.Node.enroll_hint() needs a started node (call start() first)")
        mount_flag = f" --mount {mount}" if mount else ""
        return (
            f"colca node enroll {parent_url} --pubkey {self.pubkey}{mount_flag} "
            f"--token \"${token_env}\""
        )

    # -- publishing --------------------------------------------------------

    def service(self, name: str, mount: str = "") -> Service:
        """A local Service on this node's own local door."""
        if not self._ports:
            raise RuntimeError("chaski.Node.service() needs a started node (call start() first)")
        return Service.local(
            name,
            mount,
            host="127.0.0.1",
            http_port=self._ports["api_local"],
            mqtt_port=self._ports["mqtt_local"],
            state_dir=self.data_dir / "services" / name,
        )


def _existing_ports(existing: Optional[dict[str, Any]]) -> Optional[dict[str, int]]:
    if not existing:
        return None
    try:
        return {
            "api": int(existing["api"]["addr"].rsplit(":", 1)[1]),
            "api_local": int(existing["api"]["local_addr"].rsplit(":", 1)[1]),
            "mqtt": int(existing["mqtt"]["addr"].rsplit(":", 1)[1]),
            "mqtt_local": int(existing["mqtt_local"]["addr"].rsplit(":", 1)[1]),
            "repl": int(existing["repl"]["addr"].rsplit(":", 1)[1]),
        }
    except (KeyError, ValueError, IndexError):
        return None
