"""``chaski.Node``: an embedded colcad.

A ``Node`` is a node like any other:
colcad plus the services publishing through its local door. Configuration is
generated by the SDK, never written by the integrator — loopback addresses on
high ports, a data directory under the caller's home, no TLS doors except the
uplink, ``autobind: on_new_connector``. Because the child opens the uplink
outbound and commands ride the same link, an embedded node needs no inbound
port — which is also why it has no ``/healthz`` a remote operator can reach:
enrollment reads the pubkey locally instead, and :meth:`Node.enroll_hint`
says what the operator of the PARENT does with it.

``parent`` accepts three shapes:

- ``None`` — a root, or a node not yet given a parent at all.
- a bare URL string — trust-on-first-use: the parent's pubkey is read once
  from its unauthenticated ``GET /healthz`` and pinned into the data
  directory. Every later ``start()`` re-checks that URL still presents the
  same key and refuses a mismatch (the standard SSH TOFU contract: the trust
  DECISION is made once, but a changed key is never accepted silently).
- ``(url, pubkey)`` — an explicit pin: the parent's REPLICATION door as
  reachable from here and its pubkey, the two values the parent's operator
  hands out, used verbatim (a host process behind a port remap cannot derive
  that door from the parent's own address). This IS the re-pin mechanism a
  mismatch error tells the caller to use.
"""

from __future__ import annotations

import json
import os
import logging
import secrets
import shutil
import ssl
import subprocess
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import deque
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Optional, Union

import ulid as ulid_lib
import yaml

from .service import LocalDoor, Service

logger = logging.getLogger(__name__)

_COLCAD_ENV = "COLCAD_BINARY"

# The embedded case is never anything else (design §3.1): a bound
# growth-triggered catalogue is the whole point of running a node instead of
# hand-crafting a `_Signal`. Not a constructor parameter — there is exactly
# one way to run an embedded node, so there is nothing to parameterise.
_AUTOBIND = "on_new_connector"

# colcad's combined stdout/stderr, size-rotated: one backup kept, which is
# enough to survive a restart-loop without unbounded growth on the caller's
# disk (the same "bounded, not unbounded" rule every log sink in this
# codebase follows — "Every service publishes its log").
_MAX_LOG_BYTES = 10 * 1024 * 1024
# How many trailing lines a crash report carries (design §3.1: "the last ~20
# log lines").
_LOG_TAIL_LINES = 20

_HEALTHZ_TIMEOUT = 5.0
_STATUS_POLL_INTERVAL = 0.5


class NodeCrashed(RuntimeError):
    """Raised by :meth:`Node.service` and :meth:`Node.wait_enrolled` after
    colcad exited on its own. Carries the last log lines in its message —
    there is no automatic restart, so whatever comes next needs to know why."""


@dataclass
class NodeStatus:
    """One of ``stopped | starting | awaiting_enrollment | enrolled |
    offline | crashed`` (design §3.1), plus a human ``detail``: the enroll
    hint for ``awaiting_enrollment``, the last log lines for ``crashed``,
    ``None`` otherwise."""

    state: str
    detail: Optional[str] = None


_COLCAD_BUNDLE_ENV = "COLCAD_CONTRACTS_BUNDLE"


def _resolve_contracts_bundle() -> str:
    """Where colcad's contracts bundle comes from, in order: an explicit
    override (``COLCAD_CONTRACTS_BUNDLE``), then the bundle ``colcad``
    ships beside its binary. A colcad started without a bundle runs on the
    builtin floor and rejects every Colca contract — the node would enroll
    and then refuse its own service's catalogue — so this fails loudly
    instead of writing a config without one."""
    override = os.environ.get(_COLCAD_BUNDLE_ENV)
    if override:
        return override
    try:
        from colcad import BUNDLE_PATH  # type: ignore[import-not-found]
    except ImportError:
        BUNDLE_PATH = None
    if BUNDLE_PATH is not None and Path(BUNDLE_PATH).exists():
        return str(BUNDLE_PATH)
    raise RuntimeError(
        "chaski.Node could not find colcad's contracts bundle. Install `chaski[node]` "
        f"for your platform (it ships the bundle beside the binary) or set {_COLCAD_BUNDLE_ENV} "
        "to a contracts-bundle.json generated from the same source as the colcad binary "
        "(`make bundle` in a colca checkout)."
    )


def _resolve_colcad_binary() -> str:
    """Where the colcad binary comes from, in order: an explicit override
    (tests, and any caller who already has one), the platform wheel
    (``chaski[node]`` -> ``colcad``, SDK design §6/§7 gap 5), or
    whatever `colcad` resolves to on PATH."""
    import os

    override = os.environ.get(_COLCAD_ENV)
    if override:
        return override
    try:
        from colcad import BINARY_PATH  # type: ignore[import-not-found]

        # A locally path-sourced colcad (dev/lock resolution only —
        # see pyproject.toml [tool.uv.sources]) imports
        # fine but carries no binary: only scripts/build_colcad_wheels.py's
        # Go cross-compile populates bin/colcad. Trusting an unpopulated
        # BINARY_PATH would hand subprocess.Popen a path that can never
        # exist instead of falling through to PATH below.
        if Path(BINARY_PATH).exists():
            return str(BINARY_PATH)
    except ImportError:
        pass
    found = shutil.which("colcad")
    if found:
        return found
    raise RuntimeError(
        "chaski.Node could not find the colcad binary. Install `chaski[node]` "
        f"for your platform, set {_COLCAD_ENV} to a colcad binary, or put "
        "colcad on PATH."
    )


def _insecure_ssl_context() -> ssl.SSLContext:
    """No CA anywhere on a colca door (identity/authz "Node doors"): trust is
    key pinning, never a chain. Mirrors service.py's context of the same
    name — used here only to reach a PARENT's unauthenticated /healthz over
    HTTPS for TOFU, never to skip pinning the uplink itself (colcad does
    that, from the pubkey this module resolves)."""
    ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_CLIENT)
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx


def _fetch_json(url: str, timeout: float) -> dict:
    """GET url and decode its JSON body. Module-level so tests can monkeypatch
    it instead of running a real parent — the TOFU flow below is the only
    caller."""
    context = _insecure_ssl_context() if url.startswith("https://") else None
    with urllib.request.urlopen(url, timeout=timeout, context=context) as response:  # noqa: S310
        return json.load(response)


def _short(hexstr: str) -> str:
    return hexstr[:12] + "…" if len(hexstr) > 12 else hexstr


# The replication door's port, fixed by convention across every node in this
# repo ("Node doors": "Ports say what the door is") — never
# configurable from an integrator's point of view, the same way 443 always
# means the API door. `parent=` names the PARENT'S API/enrollment door (the
# door enrollment goes to, and the only one that serves an
# unauthenticated /healthz — the replication door does not); the uplink
# colcad actually dials is that same host on this fixed port instead.
_REPL_PORT = 9443


def _api_url(repl_url: str) -> str:
    """The parent's API/enrollment door for the same host as an explicit
    replication-door pin: scheme and host, the API door's default port —
    what enroll_hint()/retire_hint() print."""
    parsed = urllib.parse.urlsplit(repl_url if "://" in repl_url else f"https://{repl_url}")
    if not parsed.hostname:
        raise ValueError(f"chaski.Node: could not parse a host out of parent url {repl_url!r}")
    return f"{parsed.scheme}://{parsed.hostname}"


def _repl_url(api_url: str) -> str:
    parsed = urllib.parse.urlsplit(api_url if "://" in api_url else f"https://{api_url}")
    if not parsed.hostname:
        raise ValueError(f"chaski.Node: could not parse a host out of parent url {api_url!r}")
    return f"{parsed.scheme}://{parsed.hostname}:{_REPL_PORT}"


class _RotatingLogWriter:
    """A minimal size-based rotating sink for colcad's combined stdout/stderr
    (design §3.1: "<data_dir>/colcad.log, rotated"). colcad's OWN verbosity
    is controlled by the config's log_level field (set from Node's
    constructor arg, unchanged since the earlier version of this class) —
    this only bounds how much of it accumulates on disk."""

    def __init__(self, path: Path, max_bytes: int = _MAX_LOG_BYTES) -> None:
        self._path = path
        self._max_bytes = max_bytes
        self._path.parent.mkdir(parents=True, exist_ok=True)
        self._fh = open(self._path, "ab")  # noqa: SIM115 - lives for the writer's lifetime

    def write(self, data: bytes) -> None:
        self._fh.write(data)
        self._fh.flush()
        if self._fh.tell() >= self._max_bytes:
            self._rotate()

    def _rotate(self) -> None:
        self._fh.close()
        backup = self._path.with_name(self._path.name + ".1")
        backup.unlink(missing_ok=True)
        self._path.rename(backup)
        self._fh = open(self._path, "ab")  # noqa: SIM115 - lives for the writer's lifetime

    def close(self) -> None:
        self._fh.close()


class Node:
    """An embedded colca node: colcad as a supervised subprocess."""

    def __init__(
        self,
        name: str,
        *,
        parent: Optional[Union[str, tuple[str, str]]] = None,
        data_dir: Optional[Union[str, Path]] = None,
        retention: Optional[str] = None,
        log_level: str = "info",
        binary: Optional[str] = None,
        contracts_bundle: Optional[str] = None,
    ) -> None:
        """``parent`` is ``None`` (root / not yet enrolled), a bare URL
        (trust-on-first-use), or ``(url, pubkey)`` (an explicit pin — see the
        module docstring). ``retention`` is a Go duration string
        (e.g. ``"336h"``) applied to the node's metrics stream retention;
        ``None`` leaves colcad's own default in force."""
        self.name = name
        self._parent_arg = parent
        self.data_dir = Path(data_dir).expanduser() if data_dir else (Path.home() / ".colca" / "nodes" / name)
        self.retention = retention
        self.log_level = log_level
        self._binary = binary
        self._contracts_bundle = contracts_bundle

        self._process: Optional[subprocess.Popen] = None
        self.ulid: Optional[str] = None
        self.pubkey: Optional[str] = None
        self.admin_token: Optional[str] = None
        self._ports: dict[str, int] = {}

        # Resolved by _resolve_parent(), called from _write_config(): the
        # actual (url, pubkey) colcad's config carries, whatever shape the
        # constructor argument came in.
        self.parent_url: Optional[str] = None
        self.parent_pubkey: Optional[str] = None

        # True once this process has observed uplink state "connected" —
        # the fact that turns a later "connecting" into "offline" rather
        # than "awaiting_enrollment" (status() below).
        self._ever_connected = False

        self._log_writer: Optional[_RotatingLogWriter] = None
        self._log_thread: Optional[threading.Thread] = None
        self._log_tail: "deque[str]" = deque(maxlen=_LOG_TAIL_LINES)

    # -- parent trust (TOFU) ---------------------------------------------

    def _pin_path(self) -> Path:
        return self.data_dir / "parent.pin.json"

    def _read_pin(self) -> Optional[dict[str, str]]:
        path = self._pin_path()
        if not path.exists():
            return None
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return None

    def _write_pin(self, url: str, pubkey: str) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)
        self._pin_path().write_text(json.dumps({"url": url, "pubkey": pubkey}), encoding="utf-8")

    def _resolve_parent(self) -> Optional[dict[str, str]]:
        """Turn the constructor's ``parent`` into the ``{url, pubkey}`` block
        colcad's config carries, applying TOFU for a bare URL. Sets
        ``self.parent_url``/``self.parent_pubkey`` as a side effect —
        ``self.parent_url`` is always the API/enrollment door (what
        ``enroll_hint()``/``retire_hint()`` print), while the returned
        block's ``url`` is that same host's fixed replication door
        (:data:`_repl_url`) — the one colcad's uplink actually dials."""
        if self._parent_arg is None:
            self.parent_url = self.parent_pubkey = None
            return None

        if isinstance(self._parent_arg, tuple):
            # An explicit pin names the parent's REPLICATION door verbatim —
            # the operator knows how the parent is reachable from here (a
            # remapped host port, a tunnel); no convention is applied.
            url, pubkey = self._parent_arg
            existing = self._read_pin()
            if existing and existing.get("url") == url and existing.get("pubkey") != pubkey:
                logger.info(
                    "chaski.Node: re-pinning %s from %s to %s (explicit parent= given)",
                    url,
                    _short(existing["pubkey"]),
                    _short(pubkey),
                )
            self._write_pin(url, pubkey)
            self.parent_url, self.parent_pubkey = _api_url(url), pubkey
            return {"url": url, "pubkey": pubkey}

        url = self._parent_arg
        existing = self._read_pin()
        try:
            fetched = _fetch_json(f"{url}/healthz", _HEALTHZ_TIMEOUT)
            fetched_pubkey = fetched.get("pubkey")
            if not fetched_pubkey:
                raise RuntimeError(f"{url}/healthz did not report a pubkey")
        except (urllib.error.URLError, OSError, ValueError, RuntimeError) as exc:
            if existing and existing.get("url") == url:
                logger.warning(
                    "chaski.Node: could not reach %s to re-verify its pinned key (%s) — using the pin from %s",
                    url,
                    exc,
                    self._pin_path(),
                )
                self.parent_url, self.parent_pubkey = url, existing["pubkey"]
                return {"url": _repl_url(url), "pubkey": existing["pubkey"]}
            raise RuntimeError(
                f"chaski.Node: could not reach {url}/healthz to learn its key for the first "
                f"time (trust-on-first-use needs at least one successful read): {exc}"
            ) from exc

        if existing and existing.get("url") == url and existing.get("pubkey") != fetched_pubkey:
            raise RuntimeError(
                f"chaski.Node: {url} now presents a different key than the one pinned earlier "
                f"({_short(existing['pubkey'])} -> {_short(fetched_pubkey)}). Refusing to trust "
                f"it automatically. If this key change is expected (the parent was "
                f"reprovisioned), delete {self._pin_path()} or construct Node(parent=(url, "
                f"pubkey)) with the new key to re-pin explicitly."
            )

        self._write_pin(url, fetched_pubkey)
        self.parent_url, self.parent_pubkey = url, fetched_pubkey
        return {"url": _repl_url(url), "pubkey": fetched_pubkey}

    # -- configuration -------------------------------------------------

    def _config_path(self) -> Path:
        return self.data_dir / "config.yaml"

    def _load_existing(self) -> Optional[dict[str, Any]]:
        path = self._config_path()
        if not path.exists():
            return None
        return yaml.safe_load(path.read_text(encoding="utf-8")) or None

    def _write_config(self) -> None:
        self.data_dir.mkdir(parents=True, exist_ok=True)
        (self.data_dir / "store").mkdir(exist_ok=True)
        existing = self._load_existing()
        self.ulid = (existing or {}).get("ulid") or str(ulid_lib.new())
        self.admin_token = (existing or {}).get("api", {}).get("token") or secrets.token_hex(32)
        # Every door is `:0`: the KERNEL picks the ports, colcad reports them
        # through `addr_file`, and start() reads them back. This used to pick
        # "free" ports here by binding and releasing each in turn — and on
        # Linux the kernel hands the port you just released straight back to
        # the next bind, so two doors got one port and the Service spoke MQTT
        # to what was actually the node's own HTTP door. CI only, never on a
        # Mac, and the same class of bug as colca's WebSocket door race
        # (#530): a port is owned by whoever holds it bound, and nothing else.
        self._ports = {}
        parent = self._resolve_parent()
        doc: dict[str, Any] = {
            "ulid": self.ulid,
            "name": self.name,
            "data_dir": str(self.data_dir / "store"),
            "key_file": str(self.data_dir / "node.key"),
            "contracts": {"bundle": self._contracts_bundle or _resolve_contracts_bundle()},
            "log_level": self.log_level,
            "api": {
                "addr": "127.0.0.1:0",
                "local_addr": "127.0.0.1:0",
                "token": self.admin_token,
            },
            "mqtt": {"addr": "127.0.0.1:0"},
            "mqtt_local": {"addr": "127.0.0.1:0"},
            "repl": {"addr": "127.0.0.1:0"},
            "addr_file": str(self._addr_file()),
            "plugin": {"autobind": _AUTOBIND},
        }
        if self.retention:
            doc["retention"] = {"streams": {"metrics": {"max_age": self.retention}}}
        if parent:
            doc["parent"] = parent
        self._config_path().write_text(yaml.safe_dump(doc, sort_keys=False), encoding="utf-8")

    # -- lifecycle -------------------------------------------------------

    def start(self, *, timeout: float = 30.0) -> "Node":
        """Write config, launch colcad, and wait for its local /healthz."""
        if self._process is not None and self._process.poll() is None:
            return self
        binary = self._binary or _resolve_colcad_binary()
        self._write_config()
        # A file from a previous run would name doors that are gone. colcad
        # rewrites it once ITS listeners are up; until then there must be
        # nothing to read.
        self._addr_file().unlink(missing_ok=True)
        self._log_writer = _RotatingLogWriter(self.data_dir / "colcad.log")
        self._process = subprocess.Popen(  # noqa: S603 - binary is resolved above, not shell-interpreted
            [binary, str(self._config_path())],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
        )
        self._log_thread = threading.Thread(
            target=self._drain_log,
            args=(self._process.stdout,),
            daemon=True,
        )
        self._log_thread.start()
        try:
            self._wait_addresses(timeout)
            self._wait_healthy(timeout)
        except Exception:
            self.stop()
            raise
        return self

    def _addr_file(self) -> Path:
        return self.data_dir / "addresses.json"

    def _wait_addresses(self, timeout: float) -> None:
        """Learn where colcad's doors landed. The file is written atomically
        once every listener is bound, so its existence means it is complete."""
        deadline = time.monotonic() + timeout
        path = self._addr_file()
        while time.monotonic() < deadline:
            if self._process is not None and self._process.poll() is not None:
                raise RuntimeError(self._crash_message(self._process.returncode))
            if path.exists():
                addresses = json.loads(path.read_text(encoding="utf-8"))
                self._ports = {
                    door: int(addresses[door].rsplit(":", 1)[1])
                    for door in ("api", "api_local", "mqtt", "mqtt_local", "repl")
                }
                return
            time.sleep(0.05)
        raise TimeoutError(f"chaski.Node: colcad did not report its door addresses at {path} within {timeout:.0f}s")

    def _drain_log(self, pipe: Any) -> None:
        """Runs on its own thread for the process's whole life: colcad's
        stdout must be read continuously or its pipe fills and blocks the
        child (the same reason every subprocess-supervising tool in this
        codebase never leaves PIPE unread)."""
        writer = self._log_writer
        try:
            for raw_line in iter(pipe.readline, b""):
                if writer is not None:
                    writer.write(raw_line)
                self._log_tail.append(raw_line.decode("utf-8", errors="replace").rstrip("\n"))
        finally:
            pipe.close()

    def _wait_healthy(self, timeout: float) -> None:
        deadline = time.monotonic() + timeout
        url = f"http://127.0.0.1:{self._ports['api_local']}/healthz"
        last_error: Optional[BaseException] = None
        while time.monotonic() < deadline:
            if self._process is not None and self._process.poll() is not None:
                raise RuntimeError(self._crash_message(self._process.returncode))
            try:
                payload = _fetch_json(url, 1.0)
                self.pubkey = payload.get("pubkey")
                self.ulid = payload.get("ulid") or self.ulid
                return
            except Exception as exc:  # noqa: BLE001 - retried until the deadline
                last_error = exc
            time.sleep(0.2)
        raise TimeoutError(f"colcad did not become healthy within {timeout}s: {last_error}")

    def stop(self, *, timeout: float = 10.0) -> None:
        if self._process is None:
            return
        self._process.terminate()
        try:
            self._process.wait(timeout=timeout)
        except subprocess.TimeoutExpired:
            self._process.kill()
            self._process.wait(timeout=timeout)
        self._process = None
        if self._log_thread is not None:
            self._log_thread.join(timeout=timeout)
            self._log_thread = None
        if self._log_writer is not None:
            self._log_writer.close()
            self._log_writer = None

    def __enter__(self) -> "Node":
        return self.start()

    def __exit__(self, *exc_info: Any) -> None:
        self.stop()

    # -- status ------------------------------------------------------------

    def _check_alive(self) -> None:
        """Raise NodeCrashed if the process exited on its own. Never fires
        after a deliberate stop() — that sets self._process back to None
        before returning, so there is nothing left here to observe."""
        if self._process is not None and self._process.poll() is not None:
            raise NodeCrashed(self._crash_message(self._process.returncode))

    def _crash_message(self, exit_code: Optional[int]) -> str:
        tail = "\n".join(self._log_tail) or "(no log output captured)"
        return (
            f"chaski.Node {self.name!r}: colcad exited on its own (code {exit_code}). "
            f"Last {len(self._log_tail)} log line(s):\n{tail}"
        )

    def _try_healthz(self) -> Optional[dict]:
        if not self._ports:
            return None
        try:
            return _fetch_json(f"http://127.0.0.1:{self._ports['api_local']}/healthz", 2.0)
        except Exception:  # noqa: BLE001 - "not answering yet" is the caller's answer
            return None

    def status(self) -> NodeStatus:
        """One of ``stopped | starting | awaiting_enrollment | enrolled |
        offline | crashed`` (design §3.1). Derived from colcad's own
        ``/healthz`` — never from log scraping — plus this process's own
        knowledge of the child process and, for "offline" vs
        "awaiting_enrollment", whether this Node has ever seen "connected"
        before."""
        if self._process is None:
            return NodeStatus("stopped")
        exit_code = self._process.poll()
        if exit_code is not None:
            return NodeStatus("crashed", self._crash_message(exit_code))

        healthz = self._try_healthz()
        if healthz is None:
            return NodeStatus("starting")

        uplink = healthz.get("uplink") or {"state": "none"}
        state = uplink.get("state", "none")
        if state in ("none", "connected"):
            # "none": this node has no parent — a root has nothing to enroll.
            if state == "connected":
                self._ever_connected = True
            return NodeStatus("enrolled")
        if state == "unauthorized":
            return NodeStatus("awaiting_enrollment", self.enroll_hint())
        if state == "connecting":
            if self._ever_connected:
                return NodeStatus("offline")
            return NodeStatus("awaiting_enrollment", self.enroll_hint())
        return NodeStatus("offline", f"colcad reported an unrecognized uplink state {state!r}")

    def wait_enrolled(self, timeout: float = 60.0) -> None:
        """Block until status() is "enrolled", or raise. A TimeoutError
        carries the current status's detail (the enroll hint, most often);
        a colcad crash while waiting raises NodeCrashed immediately rather
        than waiting out the deadline for a process that is never coming
        back."""
        deadline = time.monotonic() + timeout
        last: Optional[NodeStatus] = None
        while time.monotonic() < deadline:
            self._check_alive()
            last = self.status()
            if last.state == "enrolled":
                return
            time.sleep(_STATUS_POLL_INTERVAL)
        detail = f" {last.detail}" if last and last.detail else ""
        raise TimeoutError(
            f"chaski.Node {self.name!r} did not reach 'enrolled' within {timeout}s "
            f"(last status: {last.state if last else 'unknown'}).{detail}"
        )

    # -- placement ---------------------------------------------------------

    def enroll_hint(self, *, mount: Optional[str] = None, token_env: str = "COLCA_ADMIN_TOKEN") -> str:
        """The one-liner the parent's operator runs once (gap 2): this
        node's API door is loopback-only by design (no inbound port needed —
        the uplink is outbound), so enrollment reads the pubkey locally
        rather than the parent fetching /healthz itself."""
        if not self.parent_url:
            raise RuntimeError(
                f"chaski.Node {self.name!r} has no parent — enroll_hint() only makes sense for "
                "a node constructed with parent=<url or (url, pubkey)>."
            )
        if not self.pubkey or not self.ulid:
            raise RuntimeError("chaski.Node.enroll_hint() needs a started node (call start() first)")
        return (
            f"enroll this node at {self.parent_url}: author an element at {mount or self.name!r} there, then "
            f"POST /enroll with the admin token (${token_env}) and "
            f'{{"ulid": "{self.ulid}", "kind": "node", "element": "<that element id>", "pubkey": "{self.pubkey}"}}'
        )

    def retire_hint(self, *, token_env: str = "COLCA_ADMIN_TOKEN") -> str:
        """The one-liner that removes this node from its parent's registry.
        Deleting the local data directory (this node's identity and its
        durable streams) is deliberately the integrator's own act, not
        something this method does."""
        if not self.parent_url:
            raise RuntimeError(
                f"chaski.Node {self.name!r} has no parent — retire_hint() only makes sense for "
                "a node constructed with parent=<url or (url, pubkey)>."
            )
        if not self.ulid:
            raise RuntimeError("chaski.Node.retire_hint() needs a started node (call start() first)")
        return f'curl -sk -X DELETE {self.parent_url}/enroll/{self.ulid} -H "X-Colca-Token: ${token_env}"'

    # -- publishing --------------------------------------------------------

    def service(self, name: str, mount: str = "") -> Service:
        """A local Service on this node's own local door."""
        self._check_alive()
        if not self._ports:
            raise RuntimeError("chaski.Node.service() needs a started node (call start() first)")
        door = LocalDoor(
            host="127.0.0.1",
            http_port=self._ports["api_local"],
            mqtt_port=self._ports["mqtt_local"],
        )
        svc = Service(name, mount, node=door, state_dir=self.data_dir / "services" / name)
        svc.start()
        return svc
